import Navbar from "@/components/Navbar";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//     title: "Electric Car",
//     description: "Generated by create next app",
//     icons: {
//         icon: "/image/leaf.png"
//     }
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // <html lang="en">
        //     <link
        //         rel="icon"
        //         href="/image/leaf.png"
        //         type="image/svg+xml"
        //         sizes="any"
        //     ></link>
        //     <body>
        //         <Navbar />
        //         <main>
        //             {children}
        //         </main>
        //     </body>
        // </html>
        <>
            <Navbar />
            {children}
        </>
    );
}